// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc1BqPdZ0SkOeVqTmLZtn-SiOGkJ_daI0',
    appId: '1:496495793059:web:c7ec6f898df62e65d24016',
    messagingSenderId: '496495793059',
    projectId: 'educationapp-3cc2f',
    authDomain: 'educationapp-3cc2f.firebaseapp.com',
    databaseURL: 'https://educationapp-3cc2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educationapp-3cc2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzjLFsX7d-Wqf8r8hoAh6Fs_LSVDkTzr0',
    appId: '1:496495793059:android:0b09305bea1fbba4d24016',
    messagingSenderId: '496495793059',
    projectId: 'educationapp-3cc2f',
    databaseURL: 'https://educationapp-3cc2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educationapp-3cc2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOHng0hn_FeNGxQyXIt3E8BGG4x-5S5g',
    appId: '1:496495793059:ios:bb12b3a60e67016dd24016',
    messagingSenderId: '496495793059',
    projectId: 'educationapp-3cc2f',
    databaseURL: 'https://educationapp-3cc2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educationapp-3cc2f.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOHng0hn_FeNGxQyXIt3E8BGG4x-5S5g',
    appId: '1:496495793059:ios:bb12b3a60e67016dd24016',
    messagingSenderId: '496495793059',
    projectId: 'educationapp-3cc2f',
    databaseURL: 'https://educationapp-3cc2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educationapp-3cc2f.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc1BqPdZ0SkOeVqTmLZtn-SiOGkJ_daI0',
    appId: '1:496495793059:web:9821afa0c9602dded24016',
    messagingSenderId: '496495793059',
    projectId: 'educationapp-3cc2f',
    authDomain: 'educationapp-3cc2f.firebaseapp.com',
    databaseURL: 'https://educationapp-3cc2f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educationapp-3cc2f.firebasestorage.app',
  );
}
